#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
QEMU Virtual Machine Real-time Monitoring Tool
Supports synchronization with stress tests via signals, file markers, or process detection

python3 qemu_monitor.py -t 600 -i 2
python3 qemu_monitor.py -t 600 -i 2 --enable-capture --log-dir /path/to/logs
"""

import psutil
import time
import argparse
import csv
import signal
import re
import subprocess
import os
import sys
from datetime import datetime, timedelta
from collections import defaultdict
import threading

# Try to import pandas for Excel export
try:
    import pandas as pd
    PANDAS_AVAILABLE = True
except ImportError:
    PANDAS_AVAILABLE = False

# Try to import python-dotenv for .env support
try:
    from dotenv import load_dotenv, set_key
    DOTENV_AVAILABLE = True
except ImportError:
    DOTENV_AVAILABLE = False


# ==================== .env Configuration Management ====================

ENV_FILE_PATH = '.env'
ENV_REQUIRED_KEYS = ['DEVKIT_PATH', 'KSYS_PATH', 'KSYS_CONFIG_PATH', 'UB_WATCH_PATH']


def load_env_config() -> dict:
    """Load configuration from .env file

    Returns:
        dict with keys: devkit_path, ksys_path, ksys_config_path, ub_watch_path, devkit_cpu_range
    """
    config = {
        'devkit_path': '',
        'ksys_path': '',
        'ksys_config_path': '',
        'ub_watch_path': '',
        'devkit_cpu_range': '',
    }

    if DOTENV_AVAILABLE and os.path.exists(ENV_FILE_PATH):
        load_dotenv(ENV_FILE_PATH)

    # Read from environment variables (set by dotenv or system)
    config['devkit_path'] = os.environ.get('DEVKIT_PATH', '')
    config['ksys_path'] = os.environ.get('KSYS_PATH', '')
    config['ksys_config_path'] = os.environ.get('KSYS_CONFIG_PATH', '')
    config['ub_watch_path'] = os.environ.get('UB_WATCH_PATH', '')
    config['devkit_cpu_range'] = os.environ.get('DEVKIT_CPU_RANGE', '')

    return config


def save_env_config(config: dict):
    """Save configuration back to .env file"""
    env_path = ENV_FILE_PATH

    # Create .env file if not exists
    if not os.path.exists(env_path):
        with open(env_path, 'w') as f:
            f.write("# Log collection tools configuration\n")
            f.write("# Generated by qemu_monitor.py\n\n")

    # Write each key
    if DOTENV_AVAILABLE:
        if config.get('devkit_path'):
            set_key(env_path, 'DEVKIT_PATH', config['devkit_path'])
        if config.get('ksys_path'):
            set_key(env_path, 'KSYS_PATH', config['ksys_path'])
        if config.get('ksys_config_path'):
            set_key(env_path, 'KSYS_CONFIG_PATH', config['ksys_config_path'])
        if config.get('ub_watch_path'):
            set_key(env_path, 'UB_WATCH_PATH', config['ub_watch_path'])
        if config.get('devkit_cpu_range'):
            set_key(env_path, 'DEVKIT_CPU_RANGE', config['devkit_cpu_range'])
    else:
        # Fallback: manual write
        with open(env_path, 'a') as f:
            for key, value in config.items():
                if value:
                    env_key = key.upper()
                    if env_key in ENV_REQUIRED_KEYS or env_key == 'DEVKIT_CPU_RANGE':
                        f.write(f"{env_key}={value}\n")


def validate_and_prompt_missing(config: dict) -> dict:
    """Validate paths and prompt user for missing/invalid ones

    Args:
        config: dict with path configurations

    Returns:
        Updated config dict with valid paths or None for disabled tools
    """
    key_mapping = {
        'DEVKIT_PATH': 'devkit_path',
        'KSYS_PATH': 'ksys_path',
        'KSYS_CONFIG_PATH': 'ksys_config_path',
        'UB_WATCH_PATH': 'ub_watch_path',
    }

    prompt_names = {
        'DEVKIT_PATH': 'DevKit CLI path (devkit executable)',
        'KSYS_PATH': 'ksys executable path',
        'KSYS_CONFIG_PATH': 'ksys config.yaml path',
        'UB_WATCH_PATH': 'ub_watch executable path',
    }

    for env_key, config_key in key_mapping.items():
        path = config.get(config_key, '')

        # Loop until valid path provided or user skips
        while not path or not os.path.exists(path):
            print(f"\n⚠ {env_key} not configured or path invalid")
            if path:
                print(f"  Current: {path}")
            user_input = input(f"Enter {prompt_names[env_key]} (or 'skip' to disable): ").strip()

            if user_input.lower() == 'skip':
                config[config_key] = None  # Mark as disabled
                print(f"  ✓ {env_key} disabled for this session")
                break

            if os.path.exists(user_input):
                path = user_input
                config[config_key] = user_input
                print(f"  ✓ {env_key} set to: {user_input}")
            else:
                print(f"  ✗ Path does not exist: {user_input}")

    # Save updated config to .env
    save_env_config(config)
    print("\n✓ Configuration saved to .env file")
    return config


def calculate_cpu_range_from_numa(numa_nodes: list) -> str:
    """Calculate CPU core range from NUMA node IDs

    Args:
        numa_nodes: list of NUMA node IDs (e.g., [0, 1])

    Returns:
        CPU range string like "0-95,192-287"
    """
    all_cores = []

    for node in numa_nodes:
        try:
            cpulist_path = f'/sys/devices/system/node/node{node}/cpulist'
            with open(cpulist_path) as f:
                cpulist = f.read().strip()

            # Parse cpulist (e.g., "0-95" or "0,1,2,3-10")
            for part in cpulist.split(','):
                if '-' in part:
                    start, end = part.split('-')
                    all_cores.extend(range(int(start), int(end) + 1))
                else:
                    all_cores.append(int(part))
        except Exception as e:
            print(f"⚠ Failed to read CPU list for NUMA node {node}: {e}")

    if not all_cores:
        return "0-95"  # Fallback default

    # Sort and merge into ranges
    all_cores.sort()
    ranges = []
    start = all_cores[0]
    end = all_cores[0]

    for core in all_cores[1:]:
        if core == end + 1:
            end = core
        else:
            if start == end:
                ranges.append(str(start))
            else:
                ranges.append(f"{start}-{end}")
            start = core
            end = core

    # Add last range
    if start == end:
        ranges.append(str(start))
    else:
        ranges.append(f"{start}-{end}")

    return ','.join(ranges)


# ==================== LogCapture Class ====================

class LogCapture:
    """Parallel log collection with devkit, ksys, ub_watch

    Runs collection tools in background, synchronized with QEMU monitoring duration.
    All output is redirected to log files, not interfering with terminal display.
    """

    def __init__(self, config: dict, duration: int, log_dir: str, numa_nodes: list):
        """
        Args:
            config: paths from .env (devkit_path, ksys_path, ksys_config_path, ub_watch_path, devkit_cpu_range)
            duration: collection duration in seconds (same as qemu_monitor -t)
            log_dir: output directory for log files
            numa_nodes: list of NUMA nodes to monitor (for CPU range calculation)
        """
        self.config = config
        self.duration = duration
        self.log_dir = log_dir
        self.numa_nodes = numa_nodes
        self.processes = {}  # {tool_name: Popen process}
        self.log_files = {}  # {tool_name: file handle}
        self.failed_startup = []  # tools that failed to start
        self.failed_runtime = []  # tools that failed during runtime
        self.start_time = None

    def _get_cpu_range(self) -> str:
        """Get CPU range for devkit top-down command"""
        # Use configured range if available
        if self.config.get('devkit_cpu_range'):
            return self.config['devkit_cpu_range']

        # Calculate from NUMA nodes
        return calculate_cpu_range_from_numa(self.numa_nodes)

    def start(self) -> dict:
        """Start all collection processes in parallel using Popen

        Returns:
            {'success': [tool_names], 'failed': [(tool_name, error_msg)]}
        """
        self.start_time = datetime.now()
        success = []
        failed = []

        # DevKit memory tuner
        if self.config.get('devkit_path'):
            try:
                log_path = os.path.join(self.log_dir, 'devkit_mem.log')
                self.log_files['devkit_mem'] = open(log_path, 'w')
                cmd = [self.config['devkit_path'], 'tuner', 'memory',
                       '-d', str(self.duration), '-i', '3']
                print(f"  [CMD] devkit_mem: {' '.join(cmd)}")
                self.processes['devkit_mem'] = subprocess.Popen(
                    cmd, stdout=self.log_files['devkit_mem'],
                    stderr=self.log_files['devkit_mem'],
                    cwd=self.log_dir  # Run in log_dir so output files go there
                )
                success.append('devkit_mem')
                print(f"  ✓ Started devkit tuner memory (duration={self.duration}s)")
            except Exception as e:
                failed.append(('devkit_mem', str(e)))
                self.failed_startup.append('devkit_mem')
                print(f"  ✗ Failed to start devkit_mem: {e}")

        # DevKit top-down tuner
        if self.config.get('devkit_path'):
            try:
                log_path = os.path.join(self.log_dir, 'devkit_top_down.log')
                self.log_files['devkit_top_down'] = open(log_path, 'w')
                cpu_range = self._get_cpu_range()
                cmd = [self.config['devkit_path'], 'tuner', 'top-down',
                       '-d', str(self.duration), '-i', '3', '-c', cpu_range]
                print(f"  [CMD] devkit_top_down: {' '.join(cmd)}")
                self.processes['devkit_top_down'] = subprocess.Popen(
                    cmd, stdout=self.log_files['devkit_top_down'],
                    stderr=self.log_files['devkit_top_down'],
                    cwd=self.log_dir  # Run in log_dir so output files go there
                )
                success.append('devkit_top_down')
                print(f"  ✓ Started devkit tuner top-down (cpu_range={cpu_range})")
            except Exception as e:
                failed.append(('devkit_top_down', str(e)))
                self.failed_startup.append('devkit_top_down')
                print(f"  ✗ Failed to start devkit_top_down: {e}")

        # ksys
        if self.config.get('ksys_path') and self.config.get('ksys_config_path'):
            try:
                log_path = os.path.join(self.log_dir, 'ksys.log')
                self.log_files['ksys'] = open(log_path, 'w')
                cmd = [self.config['ksys_path'], 'collect',
                       '-d', str(self.duration), '-i', '3',
                       '-c', self.config['ksys_config_path']]
                print(f"  [CMD] ksys: {' '.join(cmd)}")
                self.processes['ksys'] = subprocess.Popen(
                    cmd, stdout=self.log_files['ksys'],
                    stderr=self.log_files['ksys'],
                    cwd=self.log_dir  # Run in log_dir so report.json goes there
                )
                success.append('ksys')
                print(f"  ✓ Started ksys collect (config={self.config['ksys_config_path']})")
            except Exception as e:
                failed.append(('ksys', str(e)))
                self.failed_startup.append('ksys')
                print(f"  ✗ Failed to start ksys: {e}")

        # ub_watch
        if self.config.get('ub_watch_path'):
            try:
                log_path = os.path.join(self.log_dir, 'ub_watch.log')
                self.log_files['ub_watch'] = open(log_path, 'w')
                cmd = [self.config['ub_watch_path'],
                       '-t', str(self.duration), '-i', '3']
                print(f"  [CMD] ub_watch: {' '.join(cmd)}")
                self.processes['ub_watch'] = subprocess.Popen(
                    cmd, stdout=self.log_files['ub_watch'],
                    stderr=self.log_files['ub_watch'],
                    cwd=self.log_dir  # Run in log_dir so output files go there
                )
                success.append('ub_watch')
                print(f"  ✓ Started ub_watch (duration={self.duration}s)")
            except Exception as e:
                failed.append(('ub_watch', str(e)))
                self.failed_startup.append('ub_watch')
                print(f"  ✗ Failed to start ub_watch: {e}")

        return {'success': success, 'failed': failed}

    def stop(self):
        """Stop all running processes"""
        for tool_name, proc in self.processes.items():
            if proc.poll() is None:  # Still running
                try:
                    proc.terminate()
                    proc.wait(timeout=5)
                except subprocess.TimeoutExpired:
                    proc.kill()
                except Exception:
                    pass

        # Close log file handles
        for tool_name, f in self.log_files.items():
            try:
                f.close()
            except Exception:
                pass

    def wait(self):
        """Wait for all processes to complete, track failures"""
        for tool_name, proc in self.processes.items():
            try:
                proc.wait()
                if proc.returncode != 0:
                    self.failed_runtime.append({
                        'tool': tool_name,
                        'returncode': proc.returncode,
                    })
            except Exception as e:
                self.failed_runtime.append({
                    'tool': tool_name,
                    'error': str(e),
                })

        # Close log file handles
        for tool_name, f in self.log_files.items():
            try:
                f.close()
            except Exception:
                pass

    def get_results(self) -> dict:
        """Return collection results and status

        Returns:
            {
                'success': [tool_names],
                'failed_startup': [tool_names],
                'failed_runtime': [{tool, returncode/error}],
                'log_files': {tool_name: file_path},
                'duration': actual_duration_seconds
            }
        """
        # Calculate actual duration
        actual_duration = 0
        if self.start_time:
            actual_duration = int((datetime.now() - self.start_time).total_seconds())

        # Determine successful tools
        all_tools = list(self.processes.keys())
        success = [t for t in all_tools
                   if t not in self.failed_startup and t not in [f['tool'] for f in self.failed_runtime]]

        return {
            'success': success,
            'failed_startup': self.failed_startup,
            'failed_runtime': self.failed_runtime,
            'log_files': {
                'devkit_mem': os.path.join(self.log_dir, 'devkit_mem.log'),
                'devkit_top_down': os.path.join(self.log_dir, 'devkit_top_down.log'),
                'ksys': os.path.join(self.log_dir, 'ksys.log'),
                'ub_watch': os.path.join(self.log_dir, 'ub_watch.log'),
            },
            'duration': actual_duration,
        }


# ==================== Log File Parsers ====================

def parse_devkit_top_down(log_path: str) -> dict:
    """Parse devkit_top_down.log to extract key metrics

    Returns:
        {
            'cycles_avg': average cycles across all reports,
            'instructions_avg': average instructions,
            'ipc_avg': average IPC,
            'bad_speculation': average Bad Speculation %,
            'frontend_bound': average Frontend Bound %,
            'retiring': average Retiring %,
            'backend_bound': average Backend Bound %,
            'l3_bound': average L3 Bound %,
            'mem_bound': average Mem Bound %,
            'mem_latency_bound': average Latency bound %,
            'mem_bandwidth_bound': average Bandwidth bound %,
            'report_count': number of reports parsed
        }
    """
    result = {
        'cycles': [], 'instructions': [], 'ipc': [],
        'bad_speculation': [], 'frontend_bound': [], 'retiring': [],
        'backend_bound': [], 'l3_bound': [], 'mem_bound': [],
        'mem_latency_bound': [], 'mem_bandwidth_bound': [],
        'report_count': 0
    }

    if not os.path.exists(log_path):
        return {'error': 'File not found', 'report_count': 0}

    try:
        with open(log_path, 'r', encoding='utf-8', errors='ignore') as f:
            content = f.read()

        # Split by report sections
        reports = re.split(r'TOP-DOWN Summary Report-\d+', content)

        for report in reports:
            if not report.strip():
                continue

            # Parse Cycles, Instructions, IPC
            cycles_match = re.search(r'Cycles\s+([\d,]+)', report)
            inst_match = re.search(r'Instructions\s+([\d,]+)', report)
            ipc_match = re.search(r'IPC\s+([\d.]+)', report)

            if cycles_match:
                result['cycles'].append(float(cycles_match.group(1).replace(',', '')))
            if inst_match:
                result['instructions'].append(float(inst_match.group(1).replace(',', '')))
            if ipc_match:
                result['ipc'].append(float(ipc_match.group(1)))

            # Parse top-down metrics (need to match the main categories)
            # Bad Speculation
            bad_spec_match = re.search(r'Bad Speculation\s+([\d.]+)', report)
            if bad_spec_match:
                result['bad_speculation'].append(float(bad_spec_match.group(1)))

            # Frontend Bound
            frontend_match = re.search(r'Frontend Bound\s+([\d.]+)', report)
            if frontend_match:
                result['frontend_bound'].append(float(frontend_match.group(1)))

            # Retiring
            retiring_match = re.search(r'Retiring\s+([\d.]+)', report)
            if retiring_match:
                result['retiring'].append(float(retiring_match.group(1)))

            # Backend Bound
            backend_match = re.search(r'Backend Bound\s+([\d.]+)', report)
            if backend_match:
                result['backend_bound'].append(float(backend_match.group(1)))

            # L3 Bound (under Memory Bound)
            l3_match = re.search(r'L3 Bound\s+([\d.]+)', report)
            if l3_match:
                result['l3_bound'].append(float(l3_match.group(1)))

            # Mem Bound (under Memory Bound)
            mem_match = re.search(r'Mem Bound\s+([\d.]+)', report)
            if mem_match:
                result['mem_bound'].append(float(mem_match.group(1)))

            # Latency bound (under Mem Bound)
            latency_match = re.search(r'Latency bound\s+([\d.]+)', report)
            if latency_match:
                result['mem_latency_bound'].append(float(latency_match.group(1)))

            # Bandwidth bound (under Mem Bound)
            bw_match = re.search(r'Bandwidth bound\s+([\d.]+)', report)
            if bw_match:
                result['mem_bandwidth_bound'].append(float(bw_match.group(1)))

            result['report_count'] += 1

        # Calculate averages
        avg_result = {'report_count': result['report_count']}
        for key in ['cycles', 'instructions', 'ipc', 'bad_speculation', 'frontend_bound',
                    'retiring', 'backend_bound', 'l3_bound', 'mem_bound',
                    'mem_latency_bound', 'mem_bandwidth_bound']:
            if result[key]:
                avg_result[f'{key}_avg'] = sum(result[key]) / len(result[key])
            else:
                avg_result[f'{key}_avg'] = 0.0

        return avg_result

    except Exception as e:
        return {'error': str(e), 'report_count': 0}


def parse_ksys(log_path: str) -> dict:
    """Parse ksys.log to extract Miss Latency metrics

    Returns:
        {
            'l2_miss_latency': {'cycles_max': x, 'cycles_min': y, 'cycles_avg': z},
            'l3_miss_latency': {'cycles_max': x, 'cycles_min': y, 'cycles_avg': z},
            'ipc': IPC value,
            'topdown': top-down summary data
        }
    """
    result = {
        'l2_miss_latency': {},
        'l3_miss_latency': {},
        'ipc': None,
        'topdown': {}
    }

    if not os.path.exists(log_path):
        return {'error': 'File not found'}

    try:
        with open(log_path, 'r', encoding='utf-8', errors='ignore') as f:
            content = f.read()

        # Parse Miss Latency Summary Data
        miss_latency_section = re.search(
            r'Miss Latency Summary Data.*?\n.*?\n'
            r'\|.*?latency.*?cycles_max.*?cycles_min.*?cycles_avg.*?\n'
            r'\|.*?L2 Miss Latency.*?\|.*?(\d+).*?\|.*?(\d+).*?\|.*?(\d+).*?\n'
            r'\|.*?L3 Miss Latency.*?\|.*?(\d+).*?\|.*?(\d+).*?\|.*?(\d+).*?\n',
            content, re.DOTALL
        )

        if miss_latency_section:
            result['l2_miss_latency'] = {
                'cycles_max': int(miss_latency_section.group(1)),
                'cycles_min': int(miss_latency_section.group(2)),
                'cycles_avg': int(miss_latency_section.group(3))
            }
            result['l3_miss_latency'] = {
                'cycles_max': int(miss_latency_section.group(4)),
                'cycles_min': int(miss_latency_section.group(5)),
                'cycles_avg': int(miss_latency_section.group(6))
            }

        # Alternative simpler parsing if above fails
        if not result['l2_miss_latency']:
            l2_match = re.search(r'L2 Miss Latency.*?\|.*?(\d+).*?\|.*?(\d+).*?\|.*?(\d+)', content)
            if l2_match:
                result['l2_miss_latency'] = {
                    'cycles_max': int(l2_match.group(1)),
                    'cycles_min': int(l2_match.group(2)),
                    'cycles_avg': int(l2_match.group(3))
                }

            l3_match = re.search(r'L3 Miss Latency.*?\|.*?(\d+).*?\|.*?(\d+).*?\|.*?(\d+)', content)
            if l3_match:
                result['l3_miss_latency'] = {
                    'cycles_max': int(l3_match.group(1)),
                    'cycles_min': int(l3_match.group(2)),
                    'cycles_avg': int(l3_match.group(3))
                }

        # Parse IPC
        ipc_match = re.search(r'IPC\s*\|\s*([\d.]+)', content)
        if ipc_match:
            result['ipc'] = float(ipc_match.group(1))

        # Parse Topdown Summary
        retiring_match = re.search(r'Retiring\(%?\)\s*\|\s*([\d.]+)', content)
        frontend_match = re.search(r'Frontend Bound\(%?\)\s*\|\s*([\d.]+)', content)
        bad_spec_match = re.search(r'Bad Speculation\(%?\)\s*\|\s*([\d.]+)', content)
        backend_match = re.search(r'Backend Bound\(%?\)\s*\|\s*([\d.]+)', content)

        result['topdown'] = {
            'retiring': float(retiring_match.group(1)) if retiring_match else None,
            'frontend_bound': float(frontend_match.group(1)) if frontend_match else None,
            'bad_speculation': float(bad_spec_match.group(1)) if bad_spec_match else None,
            'backend_bound': float(backend_match.group(1)) if backend_match else None,
        }

        return result

    except Exception as e:
        return {'error': str(e)}


def parse_devkit_mem(log_path: str, numa_nodes: list = None) -> dict:
    """Parse devkit_mem.log to extract cache miss and bandwidth metrics

    Args:
        log_path: path to devkit_mem.log
        numa_nodes: list of NUMA nodes to filter bandwidth (e.g., [0, 1])

    Returns:
        {
            'cache_miss': {'L1D': x%, 'L1I': y%, 'L2D': z%, 'L2I': w%},
            'ddr_bandwidth_system': {'write': MB/s, 'read': MB/s},
            'numa_bandwidth': {node_id: {'read': MB/s, 'write': MB/s}},
            'report_count': number of reports
        }
    """
    result = {
        'cache_miss': {'L1D': [], 'L1I': [], 'L2D': [], 'L2I': []},
        'ddr_bandwidth_system': {'write': [], 'read': []},
        'numa_bandwidth': {},
        'report_count': 0
    }

    if not os.path.exists(log_path):
        return {'error': 'File not found', 'report_count': 0}

    try:
        with open(log_path, 'r', encoding='utf-8', errors='ignore') as f:
            content = f.read()

        # Split by report sections
        reports = re.split(r'Memory Summary Report-\d+', content)

        for report in reports:
            if not report.strip():
                continue

            # Parse Percentage of core Cache miss
            l1d_match = re.search(r'L1D\s+([\d.]+)%', report)
            l1i_match = re.search(r'L1I\s+([\d.]+)%', report)
            l2d_match = re.search(r'L2D\s+([\d.]+)%', report)
            l2i_match = re.search(r'L2I\s+([\d.]+)%', report)

            if l1d_match:
                result['cache_miss']['L1D'].append(float(l1d_match.group(1)))
            if l1i_match:
                result['cache_miss']['L1I'].append(float(l1i_match.group(1)))
            if l2d_match:
                result['cache_miss']['L2D'].append(float(l2d_match.group(1)))
            if l2i_match:
                result['cache_miss']['L2I'].append(float(l2i_match.group(1)))

            # Parse DDR Bandwidth (system wide)
            write_match = re.search(r'ddrc_write\s+([\d.]+)MB/s', report)
            read_match = re.search(r'ddrc_read\s+([\d.]+)MB/s', report)

            if write_match:
                result['ddr_bandwidth_system']['write'].append(float(write_match.group(1)))
            if read_match:
                result['ddr_bandwidth_system']['read'].append(float(read_match.group(1)))

            # Parse DDRC_ACCESS_BANDWIDTH per NUMA node
            # Simpler approach: find lines starting with NUMA node number
            for line in report.split('\n'):
                # Match lines like: '  0         239.55MB/s|   39.41MB/s ... 1377.94MB/s|  231.91MB/s'
                if re.match(r'\s+[0-3]\s+[\d.]+MB/s', line):
                    node_match = re.match(r'\s+([0-3])\s+', line)
                    if node_match:
                        node_id = int(node_match.group(1))
                        # Find last two MB/s values (Total column: read|write)
                        matches = re.findall(r'([\d.]+)MB/s', line)
                        if len(matches) >= 2:
                            read_val = float(matches[-2])
                            write_val = float(matches[-1])
                            if node_id not in result['numa_bandwidth']:
                                result['numa_bandwidth'][node_id] = {'read': [], 'write': []}
                            result['numa_bandwidth'][node_id]['read'].append(read_val)
                            result['numa_bandwidth'][node_id]['write'].append(write_val)

            result['report_count'] += 1

        # Calculate averages
        avg_result = {'report_count': result['report_count']}

        # Cache miss averages
        avg_result['cache_miss'] = {}
        for key in ['L1D', 'L1I', 'L2D', 'L2I']:
            if result['cache_miss'][key]:
                avg_result['cache_miss'][key] = sum(result['cache_miss'][key]) / len(result['cache_miss'][key])
            else:
                avg_result['cache_miss'][key] = 0.0

        # DDR bandwidth system averages
        avg_result['ddr_bandwidth_system'] = {}
        for key in ['write', 'read']:
            if result['ddr_bandwidth_system'][key]:
                avg_result['ddr_bandwidth_system'][key] = sum(result['ddr_bandwidth_system'][key]) / len(result['ddr_bandwidth_system'][key])
            else:
                avg_result['ddr_bandwidth_system'][key] = 0.0

        # NUMA bandwidth averages (filter by numa_nodes if specified)
        avg_result['numa_bandwidth'] = {}
        for node_id, data in result['numa_bandwidth'].items():
            if numa_nodes and node_id not in numa_nodes:
                continue
            avg_result['numa_bandwidth'][node_id] = {
                'read': sum(data['read']) / len(data['read']) if data['read'] else 0.0,
                'write': sum(data['write']) / len(data['write']) if data['write'] else 0.0
            }

        return avg_result

    except Exception as e:
        return {'error': str(e), 'report_count': 0}


def parse_ub_watch(log_path: str) -> dict:
    """Parse ub_watch.log to extract FINAL PERFORMANCE REPORT

    Returns:
        {
            'latency': {'path': 'N0->N2', 'avg_r': ns, 'avg_w': ns, 'min_r': ns, 'min_w': ns, 'max_r': ns, 'max_w': ns},
            'bandwidth': [{chip, ports, avg_wr, avg_rd, avg_sum, max_wr, max_rd, max_sum}]
        }
    """
    result = {
        'latency': {},
        'bandwidth': []
    }

    if not os.path.exists(log_path):
        return {'error': 'File not found'}

    try:
        with open(log_path, 'r', encoding='utf-8', errors='ignore') as f:
            content = f.read()

        # Find FINAL PERFORMANCE REPORT section
        final_section = re.search(
            r'FINAL PERFORMANCE REPORT.*?Duration:.*?\n'
            r'(.*?)'
            r'\[System\] Cleanup done',
            content, re.DOTALL
        )

        if not final_section:
            return {'error': 'Final report section not found'}

        final_content = final_section.group(1)

        # Parse Latency Statistics
        latency_match = re.search(
            r'\[Latency Statistics.*?\n'
            r'Path.*?Samples.*?Avg\(R/W\).*?Min\(R/W\).*?Max\(R/W\).*?\n'
            r'(-+).*?\n'
            r'(N\d+->N\d+)\s+(\d+)\s+([\d]+)/([\d]+)\s+([\d]+)/([\d]+)\s+([\d]+)/([\d]+)',
            final_content, re.DOTALL
        )

        if latency_match:
            result['latency'] = {
                'path': latency_match.group(2),
                'samples': int(latency_match.group(3)),
                'avg_r': int(latency_match.group(4)),
                'avg_w': int(latency_match.group(5)),
                'min_r': int(latency_match.group(6)),
                'min_w': int(latency_match.group(7)),
                'max_r': int(latency_match.group(8)),
                'max_w': int(latency_match.group(9))
            }

        # Parse Bandwidth Statistics
        bw_section = re.search(
            r'\[Bandwidth Statistics.*?\n'
            r'Chip.*?Ports.*?Avg Wr.*?Avg Rd.*?Avg Sum.*?Max Wr.*?Max Rd.*?Max Sum.*?\n'
            r'(-+).*?\n(.*?)(?=\n-+|$)',
            final_content, re.DOTALL
        )

        if bw_section:
            bw_lines = bw_section.group(2).strip().split('\n')
            for line in bw_lines:
                # Parse: Chip   Ports   Avg Wr   Avg Rd   Avg Sum   Max Wr   Max Rd   Max Sum
                parts = line.strip().split()
                if len(parts) >= 8:
                    try:
                        result['bandwidth'].append({
                            'chip': int(parts[0]),
                            'ports': parts[1],
                            'avg_wr': float(parts[2]),
                            'avg_rd': float(parts[3]),
                            'avg_sum': float(parts[4]),
                            'max_wr': float(parts[5]),
                            'max_rd': float(parts[6]),
                            'max_sum': float(parts[7])
                        })
                    except ValueError:
                        continue

        return result

    except Exception as e:
        return {'error': str(e)}


def parse_all_logs(log_dir: str, numa_nodes: list = None) -> dict:
    """Parse all log files in the directory

    Args:
        log_dir: directory containing log files
        numa_nodes: list of NUMA nodes for filtering devkit_mem bandwidth

    Returns:
        {
            'devkit_top_down': parsed result,
            'devkit_mem': parsed result,
            'ksys': parsed result,
            'ub_watch': parsed result
        }
    """
    results = {}

    # Parse devkit_top_down
    top_down_path = os.path.join(log_dir, 'devkit_top_down.log')
    if os.path.exists(top_down_path):
        results['devkit_top_down'] = parse_devkit_top_down(top_down_path)

    # Parse devkit_mem
    mem_path = os.path.join(log_dir, 'devkit_mem.log')
    if os.path.exists(mem_path):
        results['devkit_mem'] = parse_devkit_mem(mem_path, numa_nodes)

    # Parse ksys
    ksys_path = os.path.join(log_dir, 'ksys.log')
    if os.path.exists(ksys_path):
        results['ksys'] = parse_ksys(ksys_path)

    # Parse ub_watch
    ub_path = os.path.join(log_dir, 'ub_watch.log')
    if os.path.exists(ub_path):
        results['ub_watch'] = parse_ub_watch(ub_path)

    return results


def export_to_excel(monitor: 'QEMUMonitor', log_dir: str, numa_nodes: list = None,
                    output_file: str = None, capture_results: dict = None) -> str:
    """Export all monitoring and parsed log data to Excel

    Args:
        monitor: QEMUMonitor instance with collected data
        log_dir: directory containing log files
        numa_nodes: list of NUMA nodes monitored
        output_file: Excel output filename (default: analysis_report.xlsx in log_dir)
        capture_results: LogCapture results (optional)

    Returns:
        Path to generated Excel file
    """
    if not PANDAS_AVAILABLE:
        print("⚠ pandas not available, skipping Excel export")
        print("  Install with: pip install pandas openpyxl")
        return None

    if output_file is None:
        output_file = os.path.join(log_dir, 'analysis_report.xlsx')

    # Parse log files
    parsed_logs = parse_all_logs(log_dir, numa_nodes)

    # Create writer for multi-sheet Excel (openpyxl required)
    try:
        with pd.ExcelWriter(output_file, engine='openpyxl') as writer:
            # ========== Sheet 1: Summary Overview ==========
            summary_data = {
                'Metric': [],
                'Value': [],
                'Unit': []
            }

            # Test metadata
            summary_data['Metric'].extend(['Test Date', 'Duration', 'Sampling Interval', 'NUMA Nodes'])
            summary_data['Value'].extend([
                datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
                f"{monitor.data[0]['timestamp'] if monitor.data else 'N/A'} ~ {monitor.data[-1]['timestamp'] if monitor.data else 'N/A'}",
                'N/A',  # Interval not stored in monitor
                ','.join(map(str, numa_nodes)) if numa_nodes else 'N/A'
            ])
            summary_data['Unit'].extend(['', '', 'seconds', ''])

            # Host machine stats
            if monitor.host_cpu_history:
                host_cpu_avg = round(sum(monitor.host_cpu_history)/len(monitor.host_cpu_history), 1)
                summary_data['Metric'].extend(['Host Avg CPU', 'Host Peak CPU', 'Host Avg Memory', 'Host Peak Memory'])
                summary_data['Value'].extend([
                    host_cpu_avg, round(monitor.peak_host_cpu, 1),
                    round(sum(h['used_mb'] for h in monitor.host_mem_history)/len(monitor.host_mem_history), 0),
                    round(monitor.peak_host_mem_mb, 0)
                ])
                summary_data['Unit'].extend(['%', '%', 'MB', 'MB'])

            # Hugepage stats
            summary_data['Metric'].extend(['Hugepage Total', 'Hugepage Avg Used', 'Hugepage Peak Used', 'Hugepage Peak Usage %'])
            summary_data['Value'].extend([
                round(monitor.hugepage_total_mb, 0),
                round(sum(monitor.hugepage_used_history)/len(monitor.hugepage_used_history), 0) if monitor.hugepage_used_history else 0,
                round(monitor.peak_hugepage_used_mb, 0),
                round((monitor.peak_hugepage_used_mb / monitor.hugepage_total_mb * 100), 1) if monitor.hugepage_total_mb > 0 else 0
            ])
            summary_data['Unit'].extend(['MB', 'MB', 'MB', '%'])

            # Swap stats
            if monitor.swap_history:
                swap_avg = round(sum(s['used_mb'] for s in monitor.swap_history)/len(monitor.swap_history), 0)
                swap_total = monitor.swap_history[0]['total_mb'] if monitor.swap_history else 0
                swap_peak_pct = round(monitor.peak_swap_used_mb / swap_total * 100, 1) if swap_total > 0 else 0
                summary_data['Metric'].extend(['Swap Total', 'Swap Avg Used', 'Swap Peak Used', 'Swap Peak Usage %'])
                summary_data['Value'].extend([round(swap_total, 0), swap_avg, round(monitor.peak_swap_used_mb, 0), swap_peak_pct])
                summary_data['Unit'].extend(['MB', 'MB', 'MB', '%'])

            # VM stats
            vm_stats = monitor.calculate_vm_stats()
            overall_stats = monitor.calculate_overall_stats(vm_stats)
            summary_data['Metric'].extend(['Total VMs', 'Alive VMs at End', 'VM Avg CPU', 'VM Peak Total CPU', 'Total Avg Memory'])
            summary_data['Value'].extend([
                overall_stats['total_vms'], monitor.last_vm_count,
                overall_stats['overall_avg_cpu'], round(monitor.peak_total_cpu, 1),
                overall_stats['total_avg_memory_mb']
            ])
            summary_data['Unit'].extend(['', '', '%', '%', 'MB'])

            df_summary = pd.DataFrame(summary_data)
            df_summary.to_excel(writer, sheet_name='Summary', index=False)

            # ========== Sheet 2: NUMA CPU Stats ==========
            numa_cpu_data = {'NUMA Node': [], 'Avg CPU (%)': [], 'Peak CPU (%)': []}
            for node in sorted(monitor.numa_cpu_history.keys()):
                hist = monitor.numa_cpu_history[node]
                if hist:
                    numa_cpu_data['NUMA Node'].append(node)
                    numa_cpu_data['Avg CPU (%)'].append(round(sum(hist)/len(hist), 1))
                    numa_cpu_data['Peak CPU (%)'].append(round(monitor.numa_cpu_peak[node], 1))
            if numa_cpu_data['NUMA Node']:
                pd.DataFrame(numa_cpu_data).to_excel(writer, sheet_name='NUMA_CPU', index=False)

            # ========== Sheet 3: NUMA Memory Stats ==========
            numa_mem_data = {'NUMA Node': [], 'Avg Used (MB)': [], 'Peak Used (MB)': [], 'Avg Usage (%)': []}
            numa_summary = defaultdict(lambda: {'used': [], 'usage': []})
            for entry in monitor.numa_memory_history:
                for n in entry['nodes']:
                    numa_summary[n['node']]['used'].append(n['used'])
                    numa_summary[n['node']]['usage'].append(n['usage'])
            for node_id in sorted(numa_summary.keys()):
                data = numa_summary[node_id]
                numa_mem_data['NUMA Node'].append(node_id)
                numa_mem_data['Avg Used (MB)'].append(round(sum(data['used'])/len(data['used']), 0) if data['used'] else 0)
                numa_mem_data['Peak Used (MB)'].append(round(max(data['used']), 0) if data['used'] else 0)
                numa_mem_data['Avg Usage (%)'].append(round(sum(data['usage'])/len(data['usage']), 1) if data['usage'] else 0)
            if numa_mem_data['NUMA Node']:
                pd.DataFrame(numa_mem_data).to_excel(writer, sheet_name='NUMA_Memory', index=False)

            # ========== Sheet 4: Hugepage Per NUMA ==========
            if monitor.hugepage_per_numa_history:
                hp_data = {'NUMA Node': [], 'Avg Total (MB)': [], 'Avg Used (MB)': [], 'Avg Usage (%)': []}
                hp_summary = defaultdict(lambda: {'total': [], 'used': [], 'usage': []})
                for entry in monitor.hugepage_per_numa_history:
                    for node_id, data in entry['nodes'].items():
                        hp_summary[node_id]['total'].append(data['total_mb'])
                        hp_summary[node_id]['used'].append(data['used_mb'])
                        hp_summary[node_id]['usage'].append(data['usage_pct'])
                for node_id in sorted(hp_summary.keys()):
                    data = hp_summary[node_id]
                    hp_data['NUMA Node'].append(node_id)
                    hp_data['Avg Total (MB)'].append(round(sum(data['total'])/len(data['total']), 0) if data['total'] else 0)
                    hp_data['Avg Used (MB)'].append(round(sum(data['used'])/len(data['used']), 0) if data['used'] else 0)
                    hp_data['Avg Usage (%)'].append(round(sum(data['usage'])/len(data['usage']), 1) if data['usage'] else 0)
                pd.DataFrame(hp_data).to_excel(writer, sheet_name='Hugepage_Per_NUMA', index=False)

            # ========== Sheet 5: VM Statistics ==========
            if vm_stats:
                vm_data = {
                    'VM Name': [v['vm_name'] for v in vm_stats],
                    'PID': [v['pid'] for v in vm_stats],
                    'Samples': [v['sample_count'] for v in vm_stats],
                    'Avg CPU (%)': [v['avg_cpu'] for v in vm_stats],
                    'Max CPU (%)': [v['max_cpu'] for v in vm_stats],
                    'Avg Memory (MB)': [v['avg_memory_mb'] for v in vm_stats],
                    'Max Memory (MB)': [v['max_memory_mb'] for v in vm_stats],
                    'Avg Hugepage (MB)': [v.get('avg_huge_mb', 0) for v in vm_stats],
                }
                pd.DataFrame(vm_data).to_excel(writer, sheet_name='VM_Stats', index=False)

            # ========== Sheet 6: DevKit Top-Down ==========
            if 'devkit_top_down' in parsed_logs and 'error' not in parsed_logs['devkit_top_down']:
                td = parsed_logs['devkit_top_down']
                td_data = {
                    'Metric': ['Cycles Avg', 'Instructions Avg', 'IPC Avg',
                              'Bad Speculation (%)', 'Frontend Bound (%)', 'Retiring (%)', 'Backend Bound (%)',
                              'L3 Bound (%)', 'Mem Bound (%)', 'Latency Bound (%)', 'Bandwidth Bound (%)'],
                    'Value': [
                        td.get('cycles_avg', 0), td.get('instructions_avg', 0), td.get('ipc_avg', 0),
                        td.get('bad_speculation_avg', 0), td.get('frontend_bound_avg', 0),
                        td.get('retiring_avg', 0), td.get('backend_bound_avg', 0),
                        td.get('l3_bound_avg', 0), td.get('mem_bound_avg', 0),
                        td.get('mem_latency_bound_avg', 0), td.get('mem_bandwidth_bound_avg', 0)
                    ],
                    'Report Count': [td.get('report_count', 0)] * 11
                }
                pd.DataFrame(td_data).to_excel(writer, sheet_name='DevKit_TopDown', index=False)

            # ========== Sheet 7: DevKit Memory ==========
            if 'devkit_mem' in parsed_logs and 'error' not in parsed_logs['devkit_mem']:
                mem = parsed_logs['devkit_mem']
                mem_data = {
                    'Metric': ['L1D Miss (%)', 'L1I Miss (%)', 'L2D Miss (%)', 'L2I Miss (%)',
                              'DDR Write (MB/s)', 'DDR Read (MB/s)'],
                    'Value': [
                        mem.get('cache_miss', {}).get('L1D', 0),
                        mem.get('cache_miss', {}).get('L1I', 0),
                        mem.get('cache_miss', {}).get('L2D', 0),
                        mem.get('cache_miss', {}).get('L2I', 0),
                        mem.get('ddr_bandwidth_system', {}).get('write', 0),
                        mem.get('ddr_bandwidth_system', {}).get('read', 0)
                    ],
                    'Report Count': [mem.get('report_count', 0)] * 6
                }
                pd.DataFrame(mem_data).to_excel(writer, sheet_name='DevKit_Memory', index=False)

                # NUMA Bandwidth as separate table
                numa_bw = mem.get('numa_bandwidth', {})
                if numa_bw:
                    bw_data = {'NUMA Node': [], 'Read (MB/s)': [], 'Write (MB/s)': []}
                    for node_id in sorted(numa_bw.keys()):
                        bw_data['NUMA Node'].append(node_id)
                        bw_data['Read (MB/s)'].append(numa_bw[node_id].get('read', 0))
                        bw_data['Write (MB/s)'].append(numa_bw[node_id].get('write', 0))
                    pd.DataFrame(bw_data).to_excel(writer, sheet_name='NUMA_Bandwidth', index=False)

            # ========== Sheet 8: KSys ==========
            if 'ksys' in parsed_logs and 'error' not in parsed_logs['ksys']:
                ksys = parsed_logs['ksys']
                ksys_data = {'Metric': [], 'Value': []}

                # Latency
                l2 = ksys.get('l2_miss_latency', {})
                l3 = ksys.get('l3_miss_latency', {})
                if l2:
                    ksys_data['Metric'].extend(['L2 Miss Latency Max', 'L2 Miss Latency Min', 'L2 Miss Latency Avg'])
                    ksys_data['Value'].extend([l2.get('cycles_max', 0), l2.get('cycles_min', 0), l2.get('cycles_avg', 0)])
                if l3:
                    ksys_data['Metric'].extend(['L3 Miss Latency Max', 'L3 Miss Latency Min', 'L3 Miss Latency Avg'])
                    ksys_data['Value'].extend([l3.get('cycles_max', 0), l3.get('cycles_min', 0), l3.get('cycles_avg', 0)])

                # IPC
                if ksys.get('ipc'):
                    ksys_data['Metric'].append('IPC')
                    ksys_data['Value'].append(ksys.get('ipc', 0))

                # Topdown
                td = ksys.get('topdown', {})
                if td:
                    for key, label in [('retiring', 'Retiring (%)'), ('frontend_bound', 'Frontend Bound (%)'),
                                       ('bad_speculation', 'Bad Speculation (%)'), ('backend_bound', 'Backend Bound (%)')]:
                        if td.get(key):
                            ksys_data['Metric'].append(label)
                            ksys_data['Value'].append(td[key])

                if ksys_data['Metric']:
                    pd.DataFrame(ksys_data).to_excel(writer, sheet_name='KSys', index=False)

            # ========== Sheet 9: UB Watch ==========
            if 'ub_watch' in parsed_logs and 'error' not in parsed_logs['ub_watch']:
                ub = parsed_logs['ub_watch']
                ub_data = {'Metric': [], 'Value': []}

                lat = ub.get('latency', {})
                if lat:
                    ub_data['Metric'].extend(['Latency Path', 'Samples', 'Avg Read (ns)', 'Avg Write (ns)',
                                             'Min Read (ns)', 'Min Write (ns)', 'Max Read (ns)', 'Max Write (ns)'])
                    ub_data['Value'].extend([
                        lat.get('path', 'N/A'), lat.get('samples', 0),
                        lat.get('avg_r', 0), lat.get('avg_w', 0),
                        lat.get('min_r', 0), lat.get('min_w', 0),
                        lat.get('max_r', 0), lat.get('max_w', 0)
                    ])

                if ub_data['Metric']:
                    pd.DataFrame(ub_data).to_excel(writer, sheet_name='UBWatch_Latency', index=False)

                # Bandwidth
                bw_list = ub.get('bandwidth', [])
                if bw_list:
                    bw_data = {
                        'Chip': [bw['chip'] for bw in bw_list],
                        'Ports': [bw['ports'] for bw in bw_list],
                        'Avg Write (MB/s)': [bw['avg_wr'] for bw in bw_list],
                        'Avg Read (MB/s)': [bw['avg_rd'] for bw in bw_list],
                        'Avg Sum (MB/s)': [bw['avg_sum'] for bw in bw_list],
                        'Max Write (MB/s)': [bw['max_wr'] for bw in bw_list],
                        'Max Read (MB/s)': [bw['max_rd'] for bw in bw_list],
                        'Max Sum (MB/s)': [bw['max_sum'] for bw in bw_list]
                    }
                    pd.DataFrame(bw_data).to_excel(writer, sheet_name='UBWatch_Bandwidth', index=False)

            # ========== Sheet 10: Raw VM Data Time Series ==========
            if monitor.data:
                raw_data = {
                    'Timestamp': [d['timestamp'] for d in monitor.data],
                    'VM Name': [d['vm_name'] for d in monitor.data],
                    'PID': [d['pid'] for d in monitor.data],
                    'CPU (%)': [d['cpu_percent'] for d in monitor.data],
                    'Memory (MB)': [d['memory_mb'] for d in monitor.data],
                    'Hugepage (MB)': [d.get('memory_huge_mb', 0) for d in monitor.data]
                }
                pd.DataFrame(raw_data).to_excel(writer, sheet_name='Raw_VM_Data', index=False)

        print(f"✓ Excel report exported: {output_file}")
        return output_file

    except ImportError:
        print("⚠ openpyxl not available, skipping Excel export")
        print("  Install with: pip install openpyxl")
        return None
    except Exception as e:
        print(f"⚠ Excel export failed: {e}")
        return None


def print_capture_summary(results: dict, log_dir: str, numa_nodes: list = None):
    """Print log collection summary at the end of monitoring

    Args:
        results: capture results from LogCapture.get_results()
        log_dir: log directory path
        numa_nodes: list of NUMA nodes for filtering devkit_mem bandwidth
    """
    print("\n" + "=" * 70)
    print("Log Collection Summary")
    print("=" * 70)

    print(f"Duration: {results['duration']}s")
    print(f"Output directory: {log_dir}/")

    # Success tools
    if results['success']:
        print(f"\n✓ Success ({len(results['success'])} tools):")
        for tool in results['success']:
            log_file = results['log_files'].get(tool, '')
            size = 0
            if os.path.exists(log_file):
                size = os.path.getsize(log_file)
            print(f"   {tool}: {log_file} ({size} bytes)")

    # Startup failures
    if results['failed_startup']:
        print(f"\n✗ Failed to start ({len(results['failed_startup'])} tools):")
        for tool in results['failed_startup']:
            print(f"   {tool}: path not configured or invalid")

    # Runtime failures
    if results['failed_runtime']:
        print(f"\n✗ Failed during runtime ({len(results['failed_runtime'])} tools):")
        for fail in results['failed_runtime']:
            tool = fail['tool']
            returncode = fail.get('returncode', 'unknown')
            print(f"   {tool}: returncode={returncode}")

    # List all log files
    print(f"\nLog files in {log_dir}:")
    for tool, path in results['log_files'].items():
        if os.path.exists(path):
            size = os.path.getsize(path)
            print(f"   {os.path.basename(path)} ({size} bytes)")
        else:
            print(f"   {os.path.basename(path)} (not created)")

    # Parse and display log contents
    print("\n" + "=" * 70)
    print("Parsed Metrics Summary")
    print("=" * 70)

    parsed = parse_all_logs(log_dir, numa_nodes)

    # devkit_top_down results
    if 'devkit_top_down' in parsed and 'error' not in parsed['devkit_top_down']:
        td = parsed['devkit_top_down']
        print(f"\n[DevKit Top-Down] ({td.get('report_count', 0)} reports)")
        print(f"  Cycles Avg:       {td.get('cycles_avg', 0):,.0f}")
        print(f"  Instructions Avg: {td.get('instructions_avg', 0):,.0f}")
        print(f"  IPC Avg:          {td.get('ipc_avg', 0):.2f}")
        print(f"  Top-down Metrics:")
        print(f"    Bad Speculation:  {td.get('bad_speculation_avg', 0):.2f}%")
        print(f"    Frontend Bound:   {td.get('frontend_bound_avg', 0):.2f}%")
        print(f"    Retiring:         {td.get('retiring_avg', 0):.2f}%")
        print(f"    Backend Bound:    {td.get('backend_bound_avg', 0):.2f}%")
        print(f"  Memory Bound Details:")
        print(f"    L3 Bound:         {td.get('l3_bound_avg', 0):.2f}%")
        print(f"    Mem Bound:        {td.get('mem_bound_avg', 0):.2f}%")
        print(f"      Latency bound:    {td.get('mem_latency_bound_avg', 0):.2f}%")
        print(f"      Bandwidth bound:  {td.get('mem_bandwidth_bound_avg', 0):.2f}%")

    # devkit_mem results
    if 'devkit_mem' in parsed and 'error' not in parsed['devkit_mem']:
        mem = parsed['devkit_mem']
        print(f"\n[DevKit Memory] ({mem.get('report_count', 0)} reports)")
        cm = mem.get('cache_miss', {})
        print(f"  Cache Miss %:")
        print(f"    L1D: {cm.get('L1D', 0):.2f}%")
        print(f"    L1I: {cm.get('L1I', 0):.2f}%")
        print(f"    L2D: {cm.get('L2D', 0):.2f}%")
        print(f"    L2I: {cm.get('L2I', 0):.2f}%")
        ddr = mem.get('ddr_bandwidth_system', {})
        print(f"  DDR Bandwidth (system):")
        print(f"    Write: {ddr.get('write', 0):.2f} MB/s")
        print(f"    Read:  {ddr.get('read', 0):.2f} MB/s")
        numa_bw = mem.get('numa_bandwidth', {})
        if numa_bw:
            print(f"  NUMA Bandwidth (filtered):")
            for node_id in sorted(numa_bw.keys()):
                bw = numa_bw[node_id]
                print(f"    NUMA {node_id}: Read {bw.get('read', 0):.2f} MB/s | Write {bw.get('write', 0):.2f} MB/s")

    # ksys results
    if 'ksys' in parsed and 'error' not in parsed['ksys']:
        ksys = parsed['ksys']
        print(f"\n[KSys]")
        l2 = ksys.get('l2_miss_latency', {})
        l3 = ksys.get('l3_miss_latency', {})
        if l2:
            print(f"  L2 Miss Latency: max={l2.get('cycles_max', 0)} min={l2.get('cycles_min', 0)} avg={l2.get('cycles_avg', 0)} cycles")
        if l3:
            print(f"  L3 Miss Latency: max={l3.get('cycles_max', 0)} min={l3.get('cycles_min', 0)} avg={l3.get('cycles_avg', 0)} cycles")
        if ksys.get('ipc'):
            print(f"  IPC: {ksys.get('ipc', 0):.2f}")
        td = ksys.get('topdown', {})
        if td:
            print(f"  Topdown:")
            if td.get('retiring'):
                print(f"    Retiring:        {td['retiring']:.2f}%")
            if td.get('frontend_bound'):
                print(f"    Frontend Bound:  {td['frontend_bound']:.2f}%")
            if td.get('bad_speculation'):
                print(f"    Bad Speculation: {td['bad_speculation']:.2f}%")
            if td.get('backend_bound'):
                print(f"    Backend Bound:   {td['backend_bound']:.2f}%")

    # ub_watch results
    if 'ub_watch' in parsed and 'error' not in parsed['ub_watch']:
        ub = parsed['ub_watch']
        print(f"\n[UB Watch]")
        lat = ub.get('latency', {})
        if lat:
            print(f"  Latency ({lat.get('path', 'N/A')}):")
            print(f"    Avg: R={lat.get('avg_r', 0)}ns W={lat.get('avg_w', 0)}ns")
            print(f"    Min: R={lat.get('min_r', 0)}ns W={lat.get('min_w', 0)}ns")
            print(f"    Max: R={lat.get('max_r', 0)}ns W={lat.get('max_w', 0)}ns")
        bw_list = ub.get('bandwidth', [])
        if bw_list:
            print(f"  Bandwidth (non-zero only):")
            for bw in bw_list:
                if bw.get('avg_sum', 0) > 0:
                    print(f"    Chip {bw.get('chip', 0)} Ports {bw.get('ports', 'N/A')}: "
                          f"Wr={bw.get('avg_wr', 0):.2f} Rd={bw.get('avg_rd', 0):.2f} Sum={bw.get('avg_sum', 0):.2f} MB/s")

    print("=" * 70)


# ==================== QEMUMonitor Class ====================

class QEMUMonitor:
    def __init__(self):
        self.running = False
        self.data = []
        self.stop_event = threading.Event()
        self.process_cache = {}
        self.numa_memory_history = []
        self.peak_total_memory_mb = 0.0
        self.peak_total_cpu = 0.0
        self.hugepage_total_mb = 0.0
        self.hugepage_free_mb = 0.0
        self.hugepage_used_mb = 0.0
        self.hugepage_used_history = []
        self.peak_hugepage_used_mb = 0.0
        self.last_vm_count = 0

        # ===================== Per-NUMA Node Hugepage Statistics =====================
        self.hugepage_per_numa = {}  # {node_id: {'total_mb': x, 'free_mb': y, 'used_mb': z}}
        self.hugepage_per_numa_history = []  # Record history
        # =====================================================================

        # ===================== Host Machine Total Resource Statistics =====================
        self.host_cpu_history = []       # [(timestamp, cpu%)]
        self.host_mem_history = []       # [(timestamp, used_mb, total_mb, usage%)]
        self.peak_host_cpu = 0.0
        self.peak_host_mem_mb = 0.0

        # ===================== Swap Statistics =====================
        self.swap_history = []           # [(timestamp, used_mb, total_mb, free_mb, usage%)]
        self.peak_swap_used_mb = 0.0
        # =====================================================================

        # ===================== Specified NUMA Node CPU Statistics =====================
        self.target_numa_nodes = [0]  # Default: monitor NUMA 0
        self.numa_cpu_history = defaultdict(list)  # key: node id, value: cpu% list
        self.numa_cpu_peak = defaultdict(float)
        self.available_numa_nodes = self.get_available_numa_nodes()
        # =====================================================================

    # ==================== NUMA Memory Statistics ====================
    def get_numa_nodes_memory(self):
        numa_nodes = []
        try:
            node_dirs = [d for d in os.listdir('/sys/devices/system/node/') if d.startswith('node') and d[4:].isdigit()]
            for node in sorted(node_dirs, key=lambda x: int(x[4:])):
                node_id = int(node[4:])
                path = f'/sys/devices/system/node/{node}/meminfo'
                with open(path) as f:
                    lines = f.read().splitlines()
                total = free = 0
                for l in lines:
                    if 'MemTotal' in l:
                        total = int(l.split()[3]) * 1024
                    if 'MemFree' in l:
                        free = int(l.split()[3]) * 1024
                used = total - free
                total_mb = round(total / 1024 / 1024, 2)
                used_mb = round(used / 1024 / 1024, 2)
                free_mb = round(free / 1024 / 1024, 2)
                usage = round(used / total * 100, 2) if total > 0 else 0.0
                numa_nodes.append({
                    'node': node_id, 'total': total_mb, 'used': used_mb, 'free': free_mb, 'usage': usage
                })
        except:
            pass
        self.numa_memory_history.append({
            'ts': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            'nodes': numa_nodes
        })
        return numa_nodes

    def collect_hugepage_stats(self):
        """Collect hugepage memory statistics (total and per-NUMA node)

        Note: /proc/meminfo only reports default hugepage size statistics.
        To get accurate totals across all hugepage sizes, we calculate from per-NUMA stats.
        """
        # First collect per-NUMA stats (this correctly handles multiple hugepage sizes)
        self.collect_hugepage_per_numa_stats()

        # Sum from per-NUMA stats for accurate total (handles 2MB + 1GB etc.)
        self.hugepage_total_mb = 0.0
        self.hugepage_free_mb = 0.0
        for node_id, stats in self.hugepage_per_numa.items():
            self.hugepage_total_mb += stats['total_mb']
            self.hugepage_free_mb += stats['free_mb']

        self.hugepage_used_mb = self.hugepage_total_mb - self.hugepage_free_mb
        self.hugepage_used_history.append(self.hugepage_used_mb)

        if self.hugepage_used_mb > self.peak_hugepage_used_mb:
            self.peak_hugepage_used_mb = self.hugepage_used_mb

        # Fallback to /proc/meminfo if per-NUMA collection failed
        if self.hugepage_total_mb == 0 and self.hugepage_per_numa == {}:
            try:
                with open("/proc/meminfo", "r") as f:
                    lines = f.read()
                huge_total = int(re.search(r"HugePages_Total:\s+(\d+)", lines).group(1))
                huge_free = int(re.search(r"HugePages_Free:\s+(\d+)", lines).group(1))
                huge_size = int(re.search(r"Hugepagesize:\s+(\d+)", lines).group(1))  # kB
                self.hugepage_total_mb = (huge_total * huge_size) / 1024
                self.hugepage_free_mb = (huge_free * huge_size) / 1024
                self.hugepage_used_mb = self.hugepage_total_mb - self.hugepage_free_mb
            except:
                pass

    def collect_hugepage_per_numa_stats(self):
        """Collect hugepage memory usage for each NUMA node"""
        self.hugepage_per_numa = {}
        try:
            node_dirs = [d for d in os.listdir('/sys/devices/system/node/') if d.startswith('node') and d[4:].isdigit()]
            for node in sorted(node_dirs, key=lambda x: int(x[4:])):
                node_id = int(node[4:])
                hugepages_dir = f'/sys/devices/system/node/{node}/hugepages'
                if not os.path.exists(hugepages_dir):
                    # Record the node even if hugepages directory doesn't exist (value is 0)
                    self.hugepage_per_numa[node_id] = {
                        'total_mb': 0.0, 'free_mb': 0.0, 'used_mb': 0.0, 'usage_pct': 0.0
                    }
                    continue

                # Calculate MB for each hugepage size independently, then sum
                total_mb = 0.0
                free_mb = 0.0

                for subdir in os.listdir(hugepages_dir):
                    if subdir.startswith('hugepages-') and subdir.endswith('kB'):
                        size_match = re.search(r'hugepages-(\d+)kB', subdir)
                        if size_match:
                            huge_size_kb = int(size_match.group(1))
                            nr_path = os.path.join(hugepages_dir, subdir, 'nr_hugepages')
                            free_path = os.path.join(hugepages_dir, subdir, 'free_hugepages')
                            pages = 0
                            free_pages = 0
                            if os.path.exists(nr_path):
                                with open(nr_path) as f:
                                    pages = int(f.read().strip())
                            if os.path.exists(free_path):
                                with open(free_path) as f:
                                    free_pages = int(f.read().strip())
                            # Convert pages × size_kb to MB for this hugepage size
                            total_mb += (pages * huge_size_kb) / 1024
                            free_mb += (free_pages * huge_size_kb) / 1024

                used_mb = total_mb - free_mb
                self.hugepage_per_numa[node_id] = {
                    'total_mb': round(total_mb, 2),
                    'free_mb': round(free_mb, 2),
                    'used_mb': round(used_mb, 2),
                    'usage_pct': round(used_mb / total_mb * 100, 1) if total_mb > 0 else 0.0
                }
        except Exception as e:
            pass

        self.hugepage_per_numa_history.append({
            'ts': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            'nodes': dict(self.hugepage_per_numa)
        })

    def print_numa_real_time(self):
        nodes = self.get_numa_nodes_memory()
        if not nodes:
            return
        print("=" * 100)
        print(f"📊 Local NUMA Node Memory Real-time Usage")
        for n in nodes:
            print(f"    NUMA Node {n['node']:>2d} | Total Memory {n['total']:>8.2f} MB | Used {n['used']:>8.2f} MB | Free {n['free']:>8.2f} MB | Usage {n['usage']:>5.1f}%")
        print("=" * 100)

    def print_final_numa_stats(self):
        if not self.numa_memory_history:
            return

        summary = defaultdict(lambda: {'used': [], 'usage': []})  # Auto-initialize, supports dynamic nodes

        for entry in self.numa_memory_history:
            for n in entry['nodes']:
                node_id = n['node']

                summary[node_id]['used'].append(n['used'])
                summary[node_id]['usage'].append(n['usage'])

        print("\n[ NUMA Node Memory Statistics Summary ]")

        for node_id in sorted(summary.keys()):
            data = summary[node_id]
            avg_used = sum(data['used']) / len(data['used'])
            max_used = max(data['used'])
            avg_usage = sum(data['usage']) / len(data['usage'])
            max_usage = max(data['usage'])
            print(f"NUMA Node {node_id:>2d} | Avg Used {avg_used:>8.2f} MB | Peak {max_used:>8.2f} MB | Avg Usage {avg_usage:>5.1f}% | Peak Usage {max_usage:.1f}%")

    # ===================== Get System NUMA Nodes =====================
    def get_available_numa_nodes(self):
        try:
            nodes = []
            for f in os.listdir('/sys/devices/system/node/'):
                if f.startswith('node') and f[4:].isdigit():
                    nodes.append(int(f[4:]))
            return sorted(nodes)
        except:
            return [0]

    # ===================== Collect Specified NUMA Node CPU Usage =====================
    def collect_numa_cpu(self):
        try:
            all_cpu = psutil.cpu_percent(interval=None, percpu=True)

            for node in self.target_numa_nodes:
                with open(f'/sys/devices/system/node/node{node}/cpulist') as f:
                    cpulist = f.read().strip()

                cores = []
                for part in cpulist.split(','):
                    if '-' in part:
                        s, e = part.split('-')
                        cores.extend(range(int(s), int(e)+1))
                    else:
                        cores.append(int(part))

                total = 0.0
                valid = 0
                for c in cores:
                    try:
                        total += all_cpu[c]
                        valid += 1
                    except:
                        pass
                avg = round(total / valid, 1) if valid > 0 else 0.0

                self.numa_cpu_history[node].append(avg)
                if avg > self.numa_cpu_peak[node]:
                    self.numa_cpu_peak[node] = avg
        except:
            pass

    # ===================== Collect Host Machine Total CPU/Memory =====================
    def collect_host_stats(self):
        try:
            cpu = psutil.cpu_percent(interval=None)
            mem = psutil.virtual_memory()
            mem_used_mb = round(mem.used / 1024 / 1024, 2)
            mem_total_mb = round(mem.total / 1024 / 1024, 2)
            mem_usage = round(mem.percent, 1)
            self.host_cpu_history.append(cpu)
            self.host_mem_history.append({
                'used_mb': mem_used_mb, 'total_mb': mem_total_mb, 'usage': mem_usage
            })
            if cpu > self.peak_host_cpu:
                self.peak_host_cpu = cpu
            if mem_used_mb > self.peak_host_mem_mb:
                self.peak_host_mem_mb = mem_used_mb
        except:
            pass

    # ===================== Collect Swap Usage =====================
    def collect_swap_stats(self):
        try:
            swap = psutil.swap_memory()
            swap_used_mb = round(swap.used / 1024 / 1024, 2)
            swap_total_mb = round(swap.total / 1024 / 1024, 2)
            swap_free_mb = round(swap.free / 1024 / 1024, 2)
            swap_usage = round(swap.percent, 1)
            self.swap_history.append({
                'used_mb': swap_used_mb, 'total_mb': swap_total_mb,
                'free_mb': swap_free_mb, 'usage': swap_usage
            })
            if swap_used_mb > self.peak_swap_used_mb:
                self.peak_swap_used_mb = swap_used_mb
        except:
            pass

    def get_vm_memory_from_numastat(self, pid):
        """Use numastat -p PID to get process memory (including hugepages)"""
        result = {'total_mb': 0.0, 'huge_mb': 0.0, 'private_mb': 0.0, 'heap_mb': 0.0, 'stack_mb': 0.0, 'per_node': {}}
        try:
            output = subprocess.run(['numastat', '-p', str(pid)], capture_output=True, text=True, timeout=5)
            if output.returncode != 0:
                return result

            lines = output.stdout.strip().split('\n')
            node_ids = []
            for line in lines:
                line = line.strip()
                if not line:
                    continue
                if line.startswith('Node'):
                    for p in line.split():
                        if p.startswith('Node'):
                            try: node_ids.append(int(p.replace('Node', '')))
                            except: pass

            for line in lines:
                vals = re.findall(r'[\d.]+', line)
                if not vals or len(vals) < len(node_ids) + 1:
                    continue
                total_val = float(vals[-1])
                if line.startswith('Huge'):
                    result['huge_mb'] = total_val
                    for i, n in enumerate(node_ids):
                        result['per_node'][n] = result['per_node'].get(n, {})
                        result['per_node'][n]['huge_mb'] = float(vals[i])
                elif line.startswith('Heap'):
                    result['heap_mb'] = total_val
                    for i, n in enumerate(node_ids):
                        result['per_node'][n] = result['per_node'].get(n, {})
                        result['per_node'][n]['heap_mb'] = float(vals[i])
                elif line.startswith('Stack'):
                    result['stack_mb'] = total_val
                    for i, n in enumerate(node_ids):
                        result['per_node'][n] = result['per_node'].get(n, {})
                        result['per_node'][n]['stack_mb'] = float(vals[i])
                elif line.startswith('Private'):
                    result['private_mb'] = total_val
                    for i, n in enumerate(node_ids):
                        result['per_node'][n] = result['per_node'].get(n, {})
                        result['per_node'][n]['private_mb'] = float(vals[i])
                elif line.startswith('Total') and '---' not in line:
                    result['total_mb'] = total_val
                    for i, n in enumerate(node_ids):
                        result['per_node'][n] = result['per_node'].get(n, {})
                        result['per_node'][n]['total_mb'] = float(vals[i])
        except:
            pass
        return result

    def get_qemu_vms_realtime(self):
        """Real physical memory: Use numastat to get (including hugepage memory)"""
        vms = []
        current_pids = set()
        current_total_mem = 0.0
        current_total_cpu = 0.0

        # Support both qemu-kvm and qemu-system process names
        qemu_process_names = ('qemu-kvm', 'qemu-system')

        for proc in psutil.process_iter(['pid', 'name', 'cmdline', 'status']):
            try:
                proc_name = proc.info['name'] or ''
                # Check if process name matches any QEMU variant
                if not any(qemu_name in proc_name for qemu_name in qemu_process_names):
                    continue

                pid = proc.info['pid']
                current_pids.add(pid)
                cmdline = ' '.join(proc.info['cmdline'] or [])
                name_match = re.search(r'-name\s+([^,\s]+)', cmdline)
                vm_name = name_match.group(1) if name_match else f"vm-{pid}"

                # ===================== [Real Physical Memory: numastat] =====================
                # Use numastat -p PID to get memory (including hugepages)
                numastat_mem = self.get_vm_memory_from_numastat(pid)
                memory_mb = numastat_mem.get('total_mb', 0.0)
                memory_huge_mb = numastat_mem.get('huge_mb', 0.0)
                memory_private_mb = numastat_mem.get('private_mb', 0.0)
                memory_heap_mb = numastat_mem.get('heap_mb', 0.0)
                memory_per_numa = numastat_mem.get('per_node', {})

                # If numastat fails, fall back to psutil
                if memory_mb <= 0:
                    try:
                        mem_info = proc.memory_info()
                        memory_mb = round(mem_info.pss / 1024 / 1024, 2)
                    except:
                        mem_info = proc.memory_info()
                        memory_mb = round(mem_info.rss / 1024 / 1024, 2)
                # =================================================================

                current_total_mem += memory_mb

                # CPU Statistics
                if pid not in self.process_cache:
                    try:
                        p = psutil.Process(pid)
                        p.cpu_percent()
                        self.process_cache[pid] = p
                        cpu = 0.0
                    except:
                        cpu = 0.0
                else:
                    try:
                        p = self.process_cache[pid]
                        cpu = p.cpu_percent()
                    except psutil.NoSuchProcess:
                        self.process_cache.pop(pid, None)
                        cpu = 0.0

                cpu = round(max(0, min(cpu, 10000)), 2)
                current_total_cpu += cpu

                vms.append({
                    'pid': pid,
                    'name': vm_name,
                    'cpu_percent': cpu,
                    'memory_mb': memory_mb,
                    'memory_huge_mb': memory_huge_mb,
                    'memory_private_mb': memory_private_mb,
                    'memory_heap_mb': memory_heap_mb,
                    'memory_per_numa': memory_per_numa,
                    'status': proc.info['status']
                })

            except:
                continue

        if current_total_mem > self.peak_total_memory_mb:
            self.peak_total_memory_mb = current_total_mem
        if current_total_cpu > self.peak_total_cpu:
            self.peak_total_cpu = current_total_cpu

        dead_pids = [p for p in self.process_cache if p not in current_pids]
        for p in dead_pids:
            self.process_cache.pop(p, None)

        return vms

    def collect_sample(self):
        """Collect one sample (full refresh each time)"""
        self.collect_hugepage_stats()
        self.collect_numa_cpu()
        self.collect_host_stats()  # Collect host machine total resources
        self.collect_swap_stats()  # Collect Swap
        vms = self.get_qemu_vms_realtime()
        self.last_vm_count = len(vms)

        timestamp = datetime.now()
        sample_data = []

        if not vms:
            return []

        for vm in vms:
            record = {
                'timestamp': timestamp.strftime('%Y-%m-%d %H:%M:%S'),
                'vm_name': vm['name'],
                'pid': vm['pid'],
                'cpu_percent': vm['cpu_percent'],
                'memory_mb': vm['memory_mb'],
                'memory_huge_mb': vm.get('memory_huge_mb', 0),
                'memory_private_mb': vm.get('memory_private_mb', 0),
                'memory_heap_mb': vm.get('memory_heap_mb', 0),
                'memory_per_numa': vm.get('memory_per_numa', {}),
                'status': vm['status']
            }
            sample_data.append(record)
            self.data.append(record)
        return sample_data

    def display_realtime_table(self, sample_data, elapsed_time, duration, check_method=""):
        """Display real-time table"""
        print('\033[2J\033[H', end='')
        print("=" * 100)
        print(f"QEMU VM Real-time Monitoring - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        print(f"Elapsed: {elapsed_time} | Target: {duration if duration else 'Infinite'} | Detection Method: {check_method}")
        print("=" * 100)

        # Real-time display of specified NUMA node CPU
        numa_str = ""
        for node in self.target_numa_nodes:
            hist = self.numa_cpu_history[node]
            current = hist[-1] if hist else 0.0
            peak = self.numa_cpu_peak[node]
            numa_str += f"NUMA{node} CPU: {current:.1f}% (Peak {peak:.1f}%)  "
        print(numa_str.strip())

        # Total Hugepages
        huge_usage = round((self.hugepage_used_mb / self.hugepage_total_mb * 100), 1) if self.hugepage_total_mb > 0 else 0.0
        print(f"📄 Hugepage Memory: Total {self.hugepage_total_mb:.0f} MB  Used {self.hugepage_used_mb:.0f} MB ({huge_usage:.1f}%)  Free {self.hugepage_free_mb:.0f} MB")

        # Per-NUMA node hugepage statistics
        if self.hugepage_per_numa:
            print("📄 Per-NUMA Node Hugepages:")
            for node_id in sorted(self.hugepage_per_numa.keys()):
                hp = self.hugepage_per_numa[node_id]
                print(f"    NUMA {node_id:>2d} | Total {hp['total_mb']:>8.0f} MB | Used {hp['used_mb']:>8.0f} MB ({hp['usage_pct']:>5.1f}%) | Free {hp['free_mb']:>8.0f} MB")

        # Host machine total resources
        if self.host_cpu_history:
            host_cpu = self.host_cpu_history[-1]
            host_mem = self.host_mem_history[-1]
            print(f"🖥️  Host Machine: CPU {host_cpu:.1f}% (Peak {self.peak_host_cpu:.1f}%) | Memory {host_mem['used_mb']:.0f}/{host_mem['total_mb']:.0f} MB ({host_mem['usage']:.1f}%, Peak {self.peak_host_mem_mb:.0f} MB)")

        # Swap
        if self.swap_history:
            s = self.swap_history[-1]
            if s['total_mb'] > 0:
                print(f"🔄 Swap:      Used {s['used_mb']:.0f}/{s['total_mb']:.0f} MB ({s['usage']:.1f}%) | Peak {self.peak_swap_used_mb:.0f} MB")
            else:
                print("🔄 Swap:      Not enabled")

        self.print_numa_real_time()

        if not sample_data:
            print("No running QEMU virtual machines detected")
            return

        # Table header: Add hugepage memory column
        header = f"{'VM Name':<28} {'PID':<10} {'CPU%':<10} {'Memory(MB)':<12} {'Hugepage(MB)':<12} {'Status':<10}"
        print(header)
        print("-" * 120)

        sorted_vms = sorted(sample_data, key=lambda x: x['cpu_percent'], reverse=True)
        for vm in sorted_vms[:15]:
            name = vm['vm_name'][:27] if len(vm['vm_name']) > 27 else vm['vm_name']
            huge_mb = vm.get('memory_huge_mb', 0.0)
            row = (f"{name:<28} {vm['pid']:<10} {vm['cpu_percent']:<10.2f} "
                   f"{vm['memory_mb']:<12.2f} {huge_mb:<12.2f} {vm['status']:<10}")
            print(row)

        if len(sorted_vms) > 15:
            print(f"... {len(sorted_vms) - 15} more virtual machines ...")

        print("-" * 120)
        print(f"Total: {len(sample_data)} virtual machines | Data points: {len(self.data)}")
        print("Press Ctrl+C to stop monitoring")

    def check_stress_process(self, stress_pattern):
        try:
            for proc in psutil.process_iter(['cmdline', 'name']):
                try:
                    cl = ' '.join(proc.info['cmdline'] or [])
                    if stress_pattern in cl or stress_pattern in (proc.info['name'] or ''):
                        return True
                except:
                    continue
            return False
        except:
            return False

    def check_stress_file(self, file_path):
        return os.path.exists(file_path)

    def wait_for_stress_and_monitor(self, check_type, check_target, interval_seconds=5):
        print(f"Waiting for stress test to start... (Detection method: {check_type}={check_target})")
        stress_started = False
        while not stress_started:
            stress_started = (self.check_stress_process(check_target) if check_type == 'process'
                              else self.check_stress_file(check_target))
            if not stress_started:
                print(f"[{datetime.now().strftime('%H:%M:%S')}] Waiting for stress test to start...")
                time.sleep(2)

        print(f"✓ Stress test detected! Starting monitoring...")
        self.running = True
        start_time = time.time()

        def handler(sig, frame):
            print("\n\nStop signal received, ending monitoring...")
            self.running = False

        signal.signal(signal.SIGINT, handler)
        signal.signal(signal.SIGTERM, handler)

        try:
            while self.running:
                loop_start = time.time()
                if check_type == 'process' and not self.check_stress_process(check_target):
                    print("\n✓ Stress process ended, stopping monitoring")
                    self.running = False
                    break
                if check_type == 'file' and not self.check_stress_file(check_target):
                    print("\n✓ Stress file removed, stopping monitoring")
                    self.running = False
                    break

                sample = self.collect_sample()
                elapsed = str(timedelta(seconds=int(time.time() - start_time)))
                self.display_realtime_table(sample, elapsed, "Stress Sync", f"{check_type}={check_target}")

                sl = max(0, interval_seconds - (time.time() - loop_start))
                if sl > 0 and self.running:
                    time.sleep(sl)
        except KeyboardInterrupt:
            pass
        return self.data

    def start_monitoring(self, duration_seconds=None, interval_seconds=5):
        self.running = True
        start_time = time.time()
        def handler(sig, frame):
            print("\nStopping monitoring...")
            self.running = False
        signal.signal(signal.SIGINT, handler)

        print(f"Starting QEMU VM monitoring...")
        print(f"Sampling interval: {interval_seconds}s | {'Run indefinitely' if not duration_seconds else f'Duration: {duration_seconds}s'}")

        try:
            while self.running:
                loop_start = time.time()
                sample = self.collect_sample()
                elapsed = time.time() - start_time
                elapsed_str = str(timedelta(seconds=int(elapsed)))
                dur_str = str(timedelta(seconds=int(duration_seconds))) if duration_seconds else "∞"
                self.display_realtime_table(sample, elapsed_str, dur_str, "Timer Mode")

                if duration_seconds and elapsed >= duration_seconds:
                    print(f"\n✓ Timer duration reached, monitoring complete")
                    self.running = False
                    break

                sl = max(0, interval_seconds - (time.time() - loop_start))
                if sl > 0 and self.running:
                    time.sleep(sl)
        except KeyboardInterrupt:
            pass
        return self.data

    def export_raw_csv(self, filename=None):
        if not filename:
            filename = f"qemu_monitor_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv"
        with open(filename, 'w', newline='', encoding='utf-8-sig') as f:
            fieldnames = ['timestamp','vm_name','pid','cpu_percent','memory_mb','memory_huge_mb','memory_private_mb','memory_heap_mb','status']
            w = csv.DictWriter(f, fieldnames, extrasaction='ignore')
            w.writeheader()
            if self.data:
                w.writerows(self.data)
        print(f"\n✓ Raw data: {filename} ({len(self.data)} rows)")
        return filename

    def calculate_vm_stats(self):
        vm_data = defaultdict(list)
        for r in self.data:
            vm_data[r['vm_name']].append(r)
        stats = []
        for name, recs in sorted(vm_data.items()):
            cpus = [r['cpu_percent'] for r in recs]
            mems = [r['memory_mb'] for r in recs]
            huge = [r.get('memory_huge_mb', 0) for r in recs]
            private = [r.get('memory_private_mb', 0) for r in recs]
            heap = [r.get('memory_heap_mb', 0) for r in recs]
            stats.append({
                'vm_name': name, 'pid': recs[0]['pid'], 'sample_count': len(recs),
                'avg_cpu': round(sum(cpus)/len(cpus),2), 'max_cpu': round(max(cpus),2),
                'avg_memory_mb': round(sum(mems)/len(mems),2), 'max_memory_mb': round(max(mems),2),
                'min_memory_mb': round(min(mems),2), 'last_memory_mb': mems[-1],
                'avg_huge_mb': round(sum(huge)/len(huge),2) if huge else 0, 'max_huge_mb': round(max(huge),2) if huge else 0,
                'avg_private_mb': round(sum(private)/len(private),2) if private else 0, 'max_private_mb': round(max(private),2) if private else 0,
                'avg_heap_mb': round(sum(heap)/len(heap),2) if heap else 0, 'max_heap_mb': round(max(heap),2) if heap else 0,
            })
        return stats

    def calculate_overall_stats(self, vm_stats):
        ac = [v['avg_cpu'] for v in vm_stats]
        am = [v['avg_memory_mb'] for v in vm_stats]
        return {
            'total_vms': len(vm_stats),
            'overall_avg_cpu': round(sum(ac)/len(ac),2) if ac else 0,
            'overall_max_cpu': round(max([v['max_cpu'] for v in vm_stats]),2) if vm_stats else 0,
            'overall_avg_memory_mb': round(sum(am)/len(am),2) if am else 0,
            'overall_max_memory_mb': round(max([v['max_memory_mb'] for v in vm_stats]),2) if vm_stats else 0,
            'total_avg_memory_mb': round(sum(am),2),
            'total_avg_memory_gb': round(sum(am)/1024,2)
        }

    def export_summary_csv(self, vm_stats, overall_stats, filename=None):
        if not filename:
            filename = f"summary_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv"
        with open(filename, 'w', newline='', encoding='utf-8-sig') as f:
            w = csv.writer(f)
            w.writerow(['=== Host Machine Statistics ===', ''])
            w.writerow(['Total VMs', f"{overall_stats['total_vms']}"])
            w.writerow(['Alive VM Count', self.last_vm_count])

            # Host machine total CPU/Memory
            host_cpu_avg = round(sum(self.host_cpu_history)/len(self.host_cpu_history), 1) if self.host_cpu_history else 0
            w.writerow([f'Host Avg CPU%', host_cpu_avg])
            w.writerow([f'Host Peak CPU%', round(self.peak_host_cpu, 1)])
            host_mem_avg_mb = round(sum(h['used_mb'] for h in self.host_mem_history)/len(self.host_mem_history), 2) if self.host_mem_history else 0
            w.writerow([f'Host Avg Memory MB', host_mem_avg_mb])
            w.writerow([f'Host Peak Memory MB', round(self.peak_host_mem_mb, 2)])

            # Export NUMA CPU statistics
            for node in sorted(self.numa_cpu_history.keys()):
                hist = self.numa_cpu_history[node]
                avg = round(sum(hist)/len(hist),1) if hist else 0
                peak = self.numa_cpu_peak[node]
                w.writerow([f'NUMA{node} Avg CPU%', avg])
                w.writerow([f'NUMA{node} Peak CPU%', peak])

            w.writerows([
                ['VM Avg CPU%', overall_stats['overall_avg_cpu']],
                ['VM Max CPU%', overall_stats['overall_max_cpu']],
                ['Peak Total CPU', round(self.peak_total_cpu, 1)],
                ['VM Avg Memory MB', overall_stats['overall_avg_memory_mb']],
                ['VM Max Memory MB', overall_stats['overall_max_memory_mb']],
                ['Total Memory MB (Avg)', overall_stats['total_avg_memory_mb']],
            ])
            w.writerow(['Hugepage Total MB', round(self.hugepage_total_mb, 0)])
            w.writerow(['Hugepage Avg Usage MB', round(sum(self.hugepage_used_history)/len(self.hugepage_used_history), 0) if self.hugepage_used_history else 0])
            w.writerow(['Hugepage Peak Usage MB', round(self.peak_hugepage_used_mb, 0)])
            huge_usage_final = round((self.peak_hugepage_used_mb / self.hugepage_total_mb * 100),1) if self.hugepage_total_mb>0 else 0
            w.writerow(['Hugepage Peak Usage %', huge_usage_final])

            # Per-NUMA node hugepage statistics
            if self.hugepage_per_numa_history:
                w.writerow([])
                w.writerow(['=== Per-NUMA Node Hugepage Statistics ==='])
                # Calculate average for each NUMA node
                numa_huge_summary = defaultdict(lambda: {'total': [], 'used': [], 'free': []})
                for entry in self.hugepage_per_numa_history:
                    for node_id, data in entry['nodes'].items():
                        numa_huge_summary[node_id]['total'].append(data['total_mb'])
                        numa_huge_summary[node_id]['used'].append(data['used_mb'])
                        numa_huge_summary[node_id]['free'].append(data['free_mb'])

                for node_id in sorted(numa_huge_summary.keys()):
                    data = numa_huge_summary[node_id]
                    avg_total = round(sum(data['total'])/len(data['total']), 0) if data['total'] else 0
                    avg_used = round(sum(data['used'])/len(data['used']), 0) if data['used'] else 0
                    avg_free = round(sum(data['free'])/len(data['free']), 0) if data['free'] else 0
                    avg_usage = round(avg_used / avg_total * 100, 1) if avg_total > 0 else 0
                    w.writerow([f'NUMA{node_id} Hugepage Total MB', avg_total])
                    w.writerow([f'NUMA{node_id} Hugepage Avg Used MB', avg_used])
                    w.writerow([f'NUMA{node_id} Hugepage Avg Free MB', avg_free])
                    w.writerow([f'NUMA{node_id} Hugepage Avg Usage %', avg_usage])

            # Swap
            swap_avg_mb = round(sum(s['used_mb'] for s in self.swap_history)/len(self.swap_history), 0) if self.swap_history else 0
            w.writerow(['Swap Total Capacity MB', round(self.swap_history[0]['total_mb'], 0) if self.swap_history else 0])
            w.writerow(['Swap Avg Usage MB', swap_avg_mb])
            w.writerow(['Swap Peak Usage MB', round(self.peak_swap_used_mb, 0)])
            swap_total = self.swap_history[0]['total_mb'] if self.swap_history else 0
            swap_peak_pct = round(self.peak_swap_used_mb / swap_total * 100, 1) if swap_total > 0 else 0
            w.writerow(['Swap Peak Usage %', swap_peak_pct])

            w.writerow([])
            w.writerow(['=== Single VM Statistics ==='])
            w.writerow(['VM','PID','Samples','avgCPU','maxCPU','avgMem','maxMem','minMem','lastMem','avgHuge','maxHuge','avgPrivate','maxPrivate','avgHeap','maxHeap'])
            for v in vm_stats:
                w.writerow([v['vm_name'],v['pid'],v['sample_count'],v['avg_cpu'],v['max_cpu'],
                            v['avg_memory_mb'],v['max_memory_mb'],v['min_memory_mb'],v['last_memory_mb'],
                            v.get('avg_huge_mb',0),v.get('max_huge_mb',0),
                            v.get('avg_private_mb',0),v.get('max_private_mb',0),
                            v.get('avg_heap_mb',0),v.get('max_heap_mb',0)])
        print(f"✓ Summary report: {filename}")
        return filename

    def print_summary_report(self, vm_stats, overall_stats):
        print("\n" + "="*85)
        print("QEMU Monitoring Summary Report")
        print("="*85)
        print(f"Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        if self.data:
            print(f"Period: {self.data[0]['timestamp']} ~ {self.data[-1]['timestamp']}")

        self.print_final_numa_stats()

        # NUMA CPU summary report
        print("\n[Specified NUMA Node CPU Statistics]")
        for node in sorted(self.numa_cpu_history.keys()):
            hist = self.numa_cpu_history[node]
            avg = round(sum(hist)/len(hist),1) if hist else 0
            peak = self.numa_cpu_peak[node]
            print(f"  NUMA {node:>2d} | Avg CPU: {avg:>5.1f}% | Peak CPU: {peak:>5.1f}%")

        print("\n[Host Machine Total Resources]")
        host_cpu_avg = round(sum(self.host_cpu_history)/len(self.host_cpu_history), 1) if self.host_cpu_history else 0
        host_mem_avg_mb = round(sum(h['used_mb'] for h in self.host_mem_history)/len(self.host_mem_history), 2) if self.host_mem_history else 0
        host_mem_total_mb = round(self.host_mem_history[0]['total_mb'], 0) if self.host_mem_history else 0
        print(f"  Host Avg CPU:  {host_cpu_avg:.1f}% (Peak {self.peak_host_cpu:.1f}%)")
        print(f"  Host Avg Memory: {host_mem_avg_mb:.0f}/{host_mem_total_mb:.0f} MB (Peak {self.peak_host_mem_mb:.0f} MB)")
        print("")
        print(f"  Total VMs:    {overall_stats['total_vms']}")
        print(f"  Alive VMs:     {self.last_vm_count}")
        print(f"  Avg CPU:       {overall_stats['overall_avg_cpu']}%")
        print(f"  Max CPU:       {overall_stats['overall_max_cpu']}%")
        print(f"  Peak Total CPU:     {round(self.peak_total_cpu, 1)}%")
        print(f"  Avg Memory:      {overall_stats['overall_avg_memory_mb']} MB")
        print(f"  Total Memory (Avg):   {overall_stats['total_avg_memory_mb']} MB ({overall_stats['total_avg_memory_gb']} GB)")
        print("[Hugepage Memory Info]")
        print(f"  Hugepage Total:     {self.hugepage_total_mb:.0f} MB")
        avg_huge = round(sum(self.hugepage_used_history)/len(self.hugepage_used_history),0) if self.hugepage_used_history else 0
        huge_usage = round((self.peak_hugepage_used_mb / self.hugepage_total_mb * 100),1) if self.hugepage_total_mb>0 else 0
        print(f"  Hugepage Avg Usage:    {avg_huge} MB")
        print(f"  Hugepage Peak Usage:    {self.peak_hugepage_used_mb:.0f} MB ({huge_usage:.1f}%)")

        # Per-NUMA node hugepage statistics
        if self.hugepage_per_numa_history:
            print("\n[Per-NUMA Node Hugepage Statistics]")
            numa_huge_summary = defaultdict(lambda: {'total': [], 'used': [], 'free': []})
            for entry in self.hugepage_per_numa_history:
                for node_id, data in entry['nodes'].items():
                    numa_huge_summary[node_id]['total'].append(data['total_mb'])
                    numa_huge_summary[node_id]['used'].append(data['used_mb'])
                    numa_huge_summary[node_id]['free'].append(data['free_mb'])

            for node_id in sorted(numa_huge_summary.keys()):
                data = numa_huge_summary[node_id]
                avg_total = round(sum(data['total'])/len(data['total']), 0) if data['total'] else 0
                avg_used = round(sum(data['used'])/len(data['used']), 0) if data['used'] else 0
                avg_free = round(sum(data['free'])/len(data['free']), 0) if data['free'] else 0
                avg_usage = round(avg_used / avg_total * 100, 1) if avg_total > 0 else 0
                print(f"  NUMA {node_id:>2d} | Total {avg_total:>8.0f} MB | Used {avg_used:>8.0f} MB ({avg_usage:>5.1f}%) | Free {avg_free:>8.0f} MB")

        # Swap
        if self.swap_history:
            swap_avg_mb = round(sum(s['used_mb'] for s in self.swap_history)/len(self.swap_history), 0) if self.swap_history else 0
            swap_total_mb = self.swap_history[0]['total_mb'] if self.swap_history else 0
            swap_peak_pct = round(self.peak_swap_used_mb / swap_total_mb * 100, 1) if swap_total_mb > 0 else 0
            print("[Swap Partition]")
            print(f"  Total Capacity:     {swap_total_mb:.0f} MB")
            print(f"  Avg Usage:    {swap_avg_mb:.0f} MB")
            print(f"  Peak Usage:    {self.peak_swap_used_mb:.0f} MB ({swap_peak_pct:.1f}%)")

        if vm_stats:
            print("\n[TOP10 CPU]")
            for i, v in enumerate(sorted(vm_stats,key=lambda x:x['avg_cpu'],reverse=True)[:10],1):
                n = v['vm_name'][:29]
                print(f"{i:2}. {n:<30} {v['avg_cpu']:6.2f}% (max {v['max_cpu']:.2f})")

            print("\n[TOP10 Memory]")
            for i, v in enumerate(sorted(vm_stats,key=lambda x:x['avg_memory_mb'],reverse=True)[:10],1):
                n = v['vm_name'][:29]
                huge_mb = v.get('avg_huge_mb', 0)
                print(f"{i:2}. {n:<30} {v['avg_memory_mb']:8.2f} MB (Hugepage {huge_mb:.2f} MB)")
        print("="*85)

    def analyze_and_export(self, raw=None, summary=None):
        vs = self.calculate_vm_stats()
        os = self.calculate_overall_stats(vs)
        rf = self.export_raw_csv(raw)
        sf = self.export_summary_csv(vs, os, summary)
        self.print_summary_report(vs, os)
        return rf, sf

def main():
    parser = argparse.ArgumentParser(
        description='QEMU Monitoring Tool',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
[Mode 1: Stress Sync Monitoring]
  sudo python3 qemu_monitor.py --stress-file /tmp/bench_running.lock
    → Wait for lock file to appear then start monitoring

[Mode 2: Timer Monitoring]
  sudo python3 qemu_monitor.py -t 60 -i 2
    → Monitor for 60 seconds

[Mode 3: With Log Collection]
  sudo python3 qemu_monitor.py -t 60 -i 2 --enable-capture
    → Monitor for 60 seconds with parallel log collection (devkit, ksys, ub_watch)
        """
    )
    sync = parser.add_mutually_exclusive_group()
    sync.add_argument('--stress-process', type=str, help='Stress process name')
    sync.add_argument('--stress-file', type=str, help='Stress marker file (e.g., /tmp/bench_running.lock)')
    parser.add_argument('-t','--time', type=int, default=60, help='Timer duration seconds (default 60)')
    parser.add_argument('-i','--interval', type=int, default=3, help='Sampling interval (default 3 seconds)')
    parser.add_argument('-o','--output', type=str, help='Output prefix')
    parser.add_argument('--numa', type=str, default='1', help='Specify NUMA nodes to monitor, comma-separated 0,1')
    parser.add_argument('--log-dir', type=str, help='Log output directory (default: logs_${timestamp}/ in current dir)')
    parser.add_argument('--enable-capture', action='store_true',
                        help='Enable parallel log collection with devkit/ksys/ub_watch')
    args = parser.parse_args()

    # Check root permission
    if hasattr(os, 'geteuid') and os.geteuid() != 0:
        print("⚠ Recommended to run as root, otherwise some processes cannot be read")
        time.sleep(1)

    # Setup log directory
    log_dir = args.log_dir or f"logs_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
    os.makedirs(log_dir, exist_ok=True)
    print(f"✓ Log directory: {log_dir}")

    # Load .env config if capture enabled
    capture = None
    if args.enable_capture:
        print("\n📋 Loading log collection configuration...")
        config = load_env_config()
        config = validate_and_prompt_missing(config)

    # Create QEMUMonitor instance
    m = QEMUMonitor()
    try:
        m.target_numa_nodes = list(map(int, args.numa.split(',')))
    except:
        m.target_numa_nodes = [0]

    # Start log capture (parallel with monitor)
    if args.enable_capture:
        print("\n🚀 Starting log collection tools...")
        capture = LogCapture(config, args.time, log_dir, m.target_numa_nodes)
        capture.start()
        print(f"✓ Log collection tools started in background (duration={args.time}s)\n")

    # Start QEMU monitoring
    if args.stress_process:
        m.wait_for_stress_and_monitor('process', args.stress_process, args.interval)
    elif args.stress_file:
        m.wait_for_stress_and_monitor('file', args.stress_file, args.interval)
    else:
        m.start_monitoring(args.time, args.interval)

    # Wait for capture to finish
    if capture:
        print("\n⏳ Waiting for log collection tools to finish...")
        capture.wait()
        print("✓ Log collection complete")

    # Export results to log_dir
    raw = os.path.join(log_dir, f"{args.output}.csv" if args.output else "qemu_monitor.csv")
    sumf = os.path.join(log_dir, f"summary_{args.output}.csv" if args.output else "summary.csv")
    m.analyze_and_export(raw, sumf)

    # Print capture summary
    capture_results = None
    if capture:
        capture_results = capture.get_results()
        print_capture_summary(capture_results, log_dir, m.target_numa_nodes)

    # Export to Excel (if pandas available)
    if PANDAS_AVAILABLE:
        excel_file = os.path.join(log_dir, 'analysis_report.xlsx')
        export_to_excel(m, log_dir, m.target_numa_nodes, excel_file, capture_results)

    print(f"\n✅ Complete! All outputs saved to: {log_dir}/")

if __name__ == '__main__':
    main()